export const GET_ALL_USER_START = "GET_ALL_USER_START";
export const GET_ALL_USER_SAGA = "GET_ALL_USER_SAGA";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SAGA = "ADD_USER_SAGA";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
